In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [23]:
import pandas as pd

df = pd.read_csv("heart.csv")

# Drop unnecessary columns
df = df.drop(["sex","dataset","cp","fbs","restecg","exang","slope","thal"], axis=1)
df.head()
df=df.fillna("0")


In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [26]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [27]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\Hanif ullah laptop\miniconda3\envs\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [28]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.4945652173913043
Accuracy of Decision Trees 0.5489130434782609


In [30]:
confusion_matrix(y_test,y_pred1)

array([[60, 13,  2,  4,  0],
       [22, 27,  3,  8,  0],
       [10,  9,  3,  0,  0],
       [ 5,  9,  3,  1,  0],
       [ 1,  4,  0,  0,  0]], dtype=int64)

In [32]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,5)))

Logistic Regression Confusion Matrix



0   1  2  3  4
0  60  13  2  4  0
1  22  27  3  8  0
2  10   9  3  0  0
3   5   9  3  1  0
4   1   4  0  0  0

In [34]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,5)))

Decision Tree Confusion Matrix



0   1  2  3  4
0  62   6  5  4  2
1  17  30  5  7  1
2   2   8  5  5  2
3   2   4  7  4  1
4   0   1  2  2  0

In [35]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [36]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
343             0                               0                         0
546             1                               0                         1
578             1                               2                         1
811             0                               1                         0
618             3                               1                         1
573             1                               1                         1
866             0                               1                         0
291             0                               0                         1
440             0                               0                         2
809             1                               3                         0

In [37]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [39]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,5)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1  2  3  4
0  60  13  2  4  0
1  22  27  3  8  0
2  10   9  3  0  0
3   5   9  3  1  0
4   1   4  0  0  0
--------------------------------------------------


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [40]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------


ValueError: Shape of passed values is (5, 5), indices imply (5, 2)

In [41]:
precision_score(y_test,y_pred1,average=None)

C:\Users\Hanif ullah laptop\miniconda3\envs\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


array([0.6122449 , 0.43548387, 0.27272727, 0.07692308, 0.        ])

In [42]:
precision_score(y_test,y_pred2,average=None)

array([0.74698795, 0.6122449 , 0.20833333, 0.18181818, 0.        ])

In [43]:
recall_score(y_test,y_pred2,average=None)

array([0.78481013, 0.5       , 0.22727273, 0.22222222, 0.        ])